In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("6-bank_customers.csv")

In [5]:
df.head()

age  job_satisfaction   balance  duration_last_call  \
0 -0.377957          1.043895  1.043494           -0.101838   
1 -0.325259          1.276263 -0.686123           -2.463205   
2  0.739019         -0.600903 -0.177294            1.335714   
3  0.474312         -1.103002  1.189936           -0.800186   
4  0.927365          1.114796  0.080284            1.261064   

   num_contacts_last_month  has_housing_loan  has_personal_loan  \
0                -1.617442          0.402713           0.913601   
1                -0.489426         -0.240715          -1.469496   
2                -0.817332         -0.790047           1.457365   
3                 0.912377         -0.406451          -1.130950   
4                 0.761179          0.921563           0.440832   

   communication_type  days_since_last_contact  campaign_response_score  \
0           -0.067192                 0.175471                -1.049646   
1            1.006633                -0.833692                 0.957744   
2           -0.218981                 0.878643                -1.257740   
3            1.985111                 1.379029                 1.041768   
4            0.184645                -1.567739                -0.142107   

   subscribed  
0           0  
1           0  
2           0  
3           1  
4           1

In [7]:
df.shape

(1000, 11)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   age                      1000 non-null   float64
 1   job_satisfaction         1000 non-null   float64
 2   balance                  1000 non-null   float64
 3   duration_last_call       1000 non-null   float64
 4   num_contacts_last_month  1000 non-null   float64
 5   has_housing_loan         1000 non-null   float64
 6   has_personal_loan        1000 non-null   float64
 7   communication_type       1000 non-null   float64
 8   days_since_last_contact  1000 non-null   float64
 9   campaign_response_score  1000 non-null   float64
 10  subscribed               1000 non-null   int64  
dtypes: float64(10), int64(1)
memory usage: 86.1 KB


In [11]:
from sklearn.model_selection import train_test_split

In [13]:
X = df.drop(columns = ["subscribed"])
y = df["subscribed"]

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X , y, test_size = 0.3, random_state=15)

In [17]:
from sklearn.linear_model import LogisticRegression

In [19]:
model = LogisticRegression()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)

In [21]:
y_pred

array([0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1])

In [23]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [29]:
score = accuracy_score(y_pred, y_test)
print("score: ",score)
print(classification_report(y_pred,y_test)) 
print("confusion matrix: \n",confusion_matrix(y_pred,y_test))

score:  0.924
              precision    recall  f1-score   support

           0       0.94      0.92      0.93       132
           1       0.91      0.93      0.92       118

    accuracy                           0.92       250
   macro avg       0.92      0.92      0.92       250
weighted avg       0.92      0.92      0.92       250

confusion matrix: 
 [[121  11]
 [  8 110]]


In [31]:
#hyperparameter tuning 

In [33]:
model2 = LogisticRegression()

In [43]:
penalty = ["l1","l2","elasticnet"]
c_values = [100, 10, 1, 0.1, 0.01]
solver_type = ["lbfgs","liblinear","saga","newton-cg","sag","newton-cholesky"]
max_iter_value = [10,100,500,1000]

In [45]:
params =dict(penalty=penalty, C=c_values, solver=solver_type, max_iter=max_iter_value)

In [47]:
params

{'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [100, 10, 1, 0.1, 0.01],
 'solver': ['lbfgs',
  'liblinear',
  'saga',
  'newton-cg',
  'sag',
  'newton-cholesky'],
 'max_iter': [10, 100, 500, 1000]}

In [75]:
#grid search cv -- verdiğimiz parametrelerş kombinasyonluyor ve en iyi sonucu verenleri bize gösteriyor

In [51]:
from sklearn.model_selection import GridSearchCV, StratifiedKFold

In [53]:
cv = StratifiedKFold()

In [57]:
grid = GridSearchCV(estimator=model2, param_grid=params, cv=cv, scoring="accuracy", n_jobs=-1)

In [61]:
grid.fit(X_train, y_train)

C:\Users\omerf\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
1000 fits failed out of a total of 1800.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
100 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\omerf\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\omerf\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\omerf\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solve

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1, 0.1, 0.01],
                         'max_iter': [10, 100, 500, 1000],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'saga', 'newton-cg',
                                    'sag', 'newton-cholesky']},
             scoring='accuracy')

In [63]:
grid.best_params_  # en iyi parametrelerimiz bunlarmış.

{'C': 0.1, 'max_iter': 10, 'penalty': 'l1', 'solver': 'liblinear'}

In [65]:
grid.best_score_  

np.float64(0.924)

In [67]:
y_pred = grid.predict(X_test)

In [69]:
score = accuracy_score(y_pred, y_test)
print("score: ",score)
print(classification_report(y_pred,y_test)) 
print("confusion matrix: \n",confusion_matrix(y_pred,y_test))

score:  0.932
              precision    recall  f1-score   support

           0       0.96      0.91      0.94       136
           1       0.90      0.96      0.93       114

    accuracy                           0.93       250
   macro avg       0.93      0.93      0.93       250
weighted avg       0.93      0.93      0.93       250

confusion matrix: 
 [[124  12]
 [  5 109]]


In [77]:
#random search CV

In [79]:
from sklearn.model_selection import RandomizedSearchCV

In [81]:
model = LogisticRegression()

In [83]:
randomcv = RandomizedSearchCV(estimator=model, param_distributions=params, scoring="accuracy", cv=5, n_iter=10) 

In [85]:
randomcv.fit(X_train,y_train)

C:\Users\omerf\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
20 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\omerf\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\omerf\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\omerf\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _c

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1, 0.1, 0.01],
                                        'max_iter': [10, 100, 500, 1000],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['lbfgs', 'liblinear', 'saga',
                                                   'newton-cg', 'sag',
                                                   'newton-cholesky']},
                   scoring='accuracy')

In [89]:
randomcv.best_params_

{'solver': 'saga', 'penalty': 'l1', 'max_iter': 100, 'C': 0.01}

In [93]:
randomcv.best_score_

np.float64(0.9213333333333331)

In [97]:
y_pred = randomcv.predict(X_test)

In [99]:
score = accuracy_score(y_pred, y_test)
print("score: ",score)
print(classification_report(y_pred,y_test)) 
print("confusion matrix: \n",confusion_matrix(y_pred,y_test))

score:  0.924
              precision    recall  f1-score   support

           0       0.95      0.90      0.93       136
           1       0.89      0.95      0.92       114

    accuracy                           0.92       250
   macro avg       0.92      0.93      0.92       250
weighted avg       0.93      0.92      0.92       250

confusion matrix: 
 [[123  13]
 [  6 108]]
